# Generated by Django 4.2.7 on 2024-04-13 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BirdClasses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('eng_name', models.TextField(null=True)),
                ('chi_name', models.TextField(null=True)),
                ('chi_description', models.TextField(blank=True, null=True)),
                ('eng_description', models.TextField(blank=True, null=True)),
                ('wiki_url', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BirdInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('eng_species', models.CharField(blank=True, max_length=30, null=True)),
                ('chi_species', models.CharField(blank=True, max_length=30, null=True)),
                ('chi_description', models.TextField(blank=True, max_length=700, null=True)),
                ('eng_description', models.TextField(blank=True, max_length=700, null=True)),
                ('wiki_url', models.TextField(blank=True, max_length=100, null=True)),
                ('bird_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='webird.birdclasses')),
            ],
        ),
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='constructing', max_length=100)),
                ('content', models.TextField(default='constructing')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, max_length=700, null=True, verbose_name='description')),
                ('img_src', models.TextField(blank=True, max_length=60, null=True)),
                ('name', models.TextField(max_length=30, null=True, verbose_name='name')),
                ('pos_x', models.PositiveSmallIntegerField(null=True)),
                ('pos_y', models.PositiveSmallIntegerField(null=True)),
                ('display', models.BooleanField(blank=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True, verbose_name='date(YYYY-MM-DD)')),
                ('num', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='num')),
                ('author', models.CharField(blank=True, max_length=30, null=True, verbose_name='author')),
                ('bird_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webird.birdinfo')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webird.location')),
            ],
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('src', models.TextField(blank=True, null=True)),
                ('ori_src', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('author', models.TextField(blank=True, null=True, verbose_name='author')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webird.location')),
                ('species', models.ManyToManyField(to='webird.birdinfo')),
            ],
        ),
    ]
