# Generated by Django 4.2.7 on 2024-04-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('link', models.TextField(auto_created=True, blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ori_img', models.ImageField(upload_to='img/ori')),
                ('sml_img', models.ImageField(upload_to='img/small')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
